### ISSUE TITLE
Upgrade to Django 2.2 LTS

### ISSUE THREAD

**Issue by tbaxter-18f** [18F/ReVAL#20]
With Django 2.2 LTS on the near horizon, we need to determine if we want to stay on the 1.11 LTS or move up to 2.x.

As a reusable app, this has implications for the consumption of the app, since 1.x projects will choke on 2.x, and 2.x may choke on 1.x.

**Comment by amymok** [comment]
I thought about this one, given the timeline for the project before (ending in March), I was worried to do the upgrade because around the time 2.2 is out and anything < 2.2 is out of support in a month of that time, our project would have ended.  Now that the project timeline is longer, it may be more possible to do this now.

**Comment by tbaxter-18f** [comment]
My concern is the downstream project impact. With USDA we control it and can handle it, but if the goal is to have additional projects using data-ingest, are we comfortable making the call that 2.x is required?

I propose we keep this open, keep an eye on the 2.2 betas and our own timeline, and make the call later in the month.
