### ISSUE TITLE
UI review output columns are swapped

### ISSUE THREAD

**Issue by cmoscardi** [18F/ReVAL#27]
Hey! I think this is extremely similar to https://github.com/18F/django-data-ingest/issues/7 , except  in the UI instead. I've included a screenshot below. Take a look at the "dollars_spent" vs. "dollars_budgeted" in row 4 (exactly the example you used in the previous issue too, funnily enough!).
![swaped_columns](https://user-images.githubusercontent.com/1095541/56992122-56963980-6b67-11e9-8d2d-67bc5a841164.png)

Specifically, I did find the issue: what's happening is in [review-errors.html](https://github.com/18F/django-data-ingest/blob/master/data_ingest/templates/data_ingest/review-errors.html#L55), the loop is using `row.data.values` when it should reference the `headers` field to maintain consistency in ordering. I think I can quickly whip up a fix, though I'm not a django templating pro specifically (I've mostly used jinja2 so this is close enough)

**Comment by cmoscardi** [comment]
Oh, wow. Django's templating language makes this somewhat more difficult, huh. 

https://stackoverflow.com/questions/8000022/django-template-how-to-look-up-a-dictionary-value-with-a-variable/8000091

This is a few years old, not sure if anything's changed? The alternatives that I see would be, 
1. preprocess on the backend (`OrderedDict` or something?)   
2. something like the custom filter suggested in the above post, which feels messy but would probably be helpful across this sort of UI with many variable columns.

**Comment by amymok** [comment]
You probably should check `row.data.keys`, or the actual key-value pair to do the rendering.  Because swapping can happen.  There are still some difference between the API version and the UI version because the API version was further developed.  The API version allows CSV in any order (here's where [reordering happens](https://github.com/18F/django-data-ingest/blob/master/data_ingest/api_views.py#L93-L127)), so to allow flexibility, we should focus on key-value pairs.  So there will be less fixing when we are ready to make the two versions use more of the same code.
